apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec: 
  replicas: 1
  template:
    spec:
      containers:
        - env:
            - name: SERVERCONTNET
              value: DEV - WebServer V1