apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webserver
  namespace: demo-3
spec:
  hosts:
    - webserver
  http:
  - route:
    - destination:
        host: webserver
        subset: v1
      weight: 80
    - destination:
        host: webserver
        subset: v2
      weight: 20