apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  ports:
    - name: web
      port: {{ .Values.proxy.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.proxy.containerPort }}
  selector:
    app: proxy
  type: LoadBalancer