apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver
    version: v1
  name: {{ .Release.Name }}-webserverv1
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.webserverv1.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webserver
      version: v1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webserver
        version: v1
    spec:
      affinity: {}
      containers:
        - env:
            - name: SERVERCONTNET
              value: {{ .Values.webserverv1.webContent }}
          image: {{ .Values.webserverv1.repository }}:{{ .Values.webserverv1.tag }}
          imagePullPolicy: IfNotPresent
          name: simpleserver
          ports:
            - containerPort: {{ .Values.webserverv1.containerPort }}
              name: web
              protocol: TCP
          resources:
            limits:
              cpu: 25m
            requests:
              cpu: 25m
