apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  ports:
    - name: http-web
      port: {{ .Values.webserver_common.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.webserver_common.containerPort }}
  selector:
    app: webserver
  type: ClusterIP