apiVersion: v1
kind: Service
metadata:
  name: webserverv1
spec:
  ports:
    - name: http-web
      port: {{ .Values.webserverv1.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.webserverv1.containerPort }}
  selector:
    app: webserver
    version: v1
  type: ClusterIP